services:
  app:
    build: .
    command: bash -c "make all; ./server"
    ports:
      - 8080:8080
    volumes:
      - .:/home/gouser/app
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: restart
          path: .
          target: /home/gouser/app